# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-service
# spec:
#   type: NodePort
#   ports:
#   - port: 80
#     targetPort: 5173
#     nodePort: 30007
#   selector:
#     app: frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
      nodePort: 30007  # Make sure this is correctly indented
  type: NodePort

